import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

import DarkModeBtn from '@/components/darkModeBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'game-loot',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <div className='w-full h-full bg-light-bg dark:bg-dark-bg'>
          <div className='flex justify-end p-2'>
            <DarkModeBtn />
          </div>
          {children}
        </div>

      </body>
    </html>
  )
}